### ISSUE TITLE
Integer comparison failed.

### ISSUE THREAD

**Issue by JulianIntronati** [pg-strom/devel#224] opened 2016-02-12 11:19 UTC
Hello,

I encounter some really strange behavior on very simple query on a bigint comparison over pg_strom gpuscan. Here is the test case.
```
\d+ flow;
```

Column | Type | Modifiers | Storage | Stats target | Description
------------ | ------------- | ------------- | ------------- | ------------- | -------------
... |
detected_proto_id | bigint | not null | plain
... |
```
SET pg_strom.enabled TO on;
SELECT detected_proto_id FROM flow f
  WHERE f.detected_proto_id = 91 LIMIT 5;
```
detected_proto_id |
------------------- |
7 |
5 |
5 |
7 |
5 |

```
SET pg_strom.enabled TO off;
SELECT detected_proto_id FROM flow f
  WHERE f.detected_proto_id = 91 LIMIT 5;
```

detected_proto_id |
------------------- |
91 |
91 |
91 |
91 |
91 |

I tried to change the type to integer because the actual data inside the table are all smaller than a int.

Here are the result:
```
\d+ flow;
```

Column | Type | Modifiers | Storage | Stats target | Description
------------ | ------------- | ------------- | ------------- | ------------- | -------------
... |
detected_proto_id | integer | not null | plain
... |

```
SET pg_strom.enabled TO on;
SELECT detected_proto_id FROM flow f
  WHERE f.detected_proto_id = 91 LIMIT 5;
```

detected_proto_id |
------------------- |
10 |
16 |
3 |
5 | 
91 |

```
SET pg_strom.enabled TO off;
SELECT detected_proto_id FROM flow f
  WHERE f.detected_proto_id = 91 LIMIT 5;
```

detected_proto_id |
------------------- |
91 |
91 |
91 |
91 |
91 |

 The query plans are :
```
SET pg_strom.enabled TO off;
EXPLAIN ANALYSE SELECT detected_proto_id FROM flow f
  WHERE f.detected_proto_id = 91 LIMIT 10;
                                                   QUERY PLAN                                                   
----------------------------------------------------------------------------------------------------------------
 Limit  (cost=0.00..63.47 rows=10 width=4) (actual time=0.015..0.019 rows=10 loops=1)
   ->  Seq Scan on flow f  (cost=0.00..595820.50 rows=93881 width=4) (actual time=0.014..0.018 rows=10 loops=1)
         Filter: (detected_proto_id = 91)
         Rows Removed by Filter: 14
 Planning time: 0.047 ms
 Execution time: 0.031 ms
(6 rows)
```
```
SET pg_strom.enabled TO on;
EXPLAIN ANALYSE SELECT detected_proto_id FROM flow f
  WHERE f.detected_proto_id = 91 LIMIT 10;
                                                            QUERY PLAN                                                            
----------------------------------------------------------------------------------------------------------------------------------
 Limit  (cost=0.00..63.47 rows=10 width=4) (actual time=10.545..10.549 rows=10 loops=1)
   ->  Custom Scan (GpuScan) on flow f  (cost=5831.24..367523.70 rows=93881 width=4) (actual time=10.543..10.545 rows=10 loops=1)
         GPU Projection: detected_proto_id
         GPU Filter: (detected_proto_id = 91)
 Planning time: 0.091 ms
 Execution time: 101.818 ms
(6 rows)
```
Here are my pg_strom settings
```
SELECT name,setting FROM pg_settings WHERE name LIKE 'pg_strom%';
              name               |  setting   
---------------------------------+------------
 pg_strom.bulkexec               | on
 pg_strom.chunk_size             | 15872
 pg_strom.chunk_size_limit_ratio | 6
 pg_strom.chunk_size_margin      | 1.25
 pg_strom.cuda_visible_devices   | 
 pg_strom.debug_cuda_coredump    | off
 pg_strom.debug_force_gpupreagg  | off
 pg_strom.debug_force_gpusort    | off
 pg_strom.debug_kernel_source    | off
 pg_strom.enable_gpuhashjoin     | on
 pg_strom.enable_gpunestloop     | on
 pg_strom.enable_gpupreagg       | on
 pg_strom.enable_gpuscan         | on
 pg_strom.enable_gpusort         | off
 pg_strom.enabled                | on
 pg_strom.gpu_dma_cost           | 1
 pg_strom.gpu_operator_cost      | 7.8125e-05
 pg_strom.gpu_setup_cost         | 4000
 pg_strom.gpu_tuple_cost         | 0.0003125
 pg_strom.max_async_tasks        | 32
 pg_strom.max_workers            | 4
 pg_strom.num_threads_margin     | 1.1
 pg_strom.perfmon                | off
 pg_strom.program_cache_size     | 49152
 pg_strom.pullup_outer_scan      | on
(25 rows)
```

Here are my gpuinfo

```
./gpuinfo
CUDA Runtime version: 7.5.0
NVIDIA Driver version: 352.63
Number of devices: 1
--------
Device Identifier: 0
Device Name: GeForce GTX 960
Global memory size: 4095MB
Maximum number of threads per block: 1024
Maximum block dimension X: 1024
Maximum block dimension Y: 1024
Maximum block dimension Z: 64
Maximum grid dimension X: 2147483647
Maximum grid dimension Y: 65535
Maximum grid dimension Z: 65535
Maximum shared memory available per block in bytes: 49152KB
Memory available on device for __constant__ variables: 65536bytes
Warp size in threads: 32
Maximum number of 32-bit registers available per block: 65536
Typical clock frequency in kilohertz: 1253000KHZ
Number of multiprocessors on device: 8
Specifies whether there is a run time limit on kernels: 1
Device is integrated with host memory: false
Device can map host memory into CUDA address space: true
Compute mode (See CUcomputemode for details): default
Device can possibly execute multiple kernels concurrently: true
Device has ECC support enabled: false
PCI bus ID of the device: 1
PCI device ID of the device: 0
Device is using TCC driver model: false
Peak memory clock frequency in kilohertz: 3505000KHZ
Global memory bus width in bits: 128
Size of L2 cache in bytes: 1048576bytes
Maximum resident threads per multiprocessor: 2048
Number of asynchronous engines: 2
Device shares a unified address space with the host: true
Major compute capability version number: 5
Minor compute capability version number: 2
Device supports stream priorities: true
Device supports caching globals in L1: false
Device supports caching locals in L1: false
Maximum shared memory available per multiprocessor: 98304bytes
Maximum number of 32bit registers per multiprocessor: 65536
Device can allocate managed memory on this system: true
Device is on a multi-GPU board: false
Unique id for a group of devices on the same multi-GPU board: 0
```
Here is my git rev :
```
git log -1
commit 97bc5ae1cc9caa8540c68a39803814274e953c5b
Author: KaiGai Kohei <kaigai@kaigai.gr.jp>
Date:   Thu Jan 28 00:06:40 2016 +0900

    CC3.0(GK104) no longer supported
```

I reduced the scope to the minimal test but I encountered this behavior in the much wider request.

If you need more tests or informations, just ask.

Best regards,
Julian.

**Comment by kaigai** [comment] 2016-02-12 11:50
It looks to me a bug. Could you give me a dataset to reproduce the problem in my environment?

Here are two suspicious points:
- GpuScan selects incorrent rows.
- Corrent rows were selected, but incorrect result was generated.

**Comment by JulianIntronati** [comment] 2016-02-12 16:38
Well, I can't give you my full set of data because of privacy.
So I did a test on reduced database without sensitive data, and the bug still there, you can download the db [here (test.psql.tar.bz2)](https://www.dropbox.com/s/vpxq60ngp8nnegs/test.psql.tar.bz2?dl=0).


I noticed some other bug, you can't dump the database with pg_strom enabled. Here is the error message :
```
pg_dump test > /tmp/test.psql
TRAP: FailedAssertion("!(var->varattno > 0 && var->varattno <= tupdesc->natts)", File: "gpuscan.c", Line: 744)
pg_dump: [archiver (db)] query failed: server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
pg_dump: [archiver (db)] query was: SELECT tableoid, oid, typname, typnamespace, typacl, (SELECT rolname FROM pg_catalog.pg_roles WHERE oid = typowner) AS rolname, typinput::oid AS typinput, typoutput::oid AS typoutput, typelem, typrelid, CASE WHEN typrelid = 0 THEN ' '::"char" ELSE (SELECT relkind FROM pg_class WHERE oid = typrelid) END AS typrelkind, typtype, typisdefined, typname[0] = '_' AND typelem != 0 AND (SELECT typarray FROM pg_type te WHERE oid = pg_type.typelem) = oid AS isarray FROM pg_type
LOG:  server process (PID 8862) was terminated by signal 6: Aborted
DETAIL:  Failed process was running: SELECT tableoid, oid, typname, typnamespace, typacl, (SELECT rolname FROM pg_catalog.pg_roles WHERE oid = typowner) AS rolname, typinput::oid AS typinput, typoutput::oid AS typoutput, typelem, typrelid, CASE WHEN typrelid = 0 THEN ' '::"char" ELSE (SELECT relkind FROM pg_class WHERE oid = typrelid) END AS typrelkind, typtype, typisdefined, typname[0] = '_' AND typelem != 0 AND (SELECT typarray FROM pg_type te WHERE oid = pg_type.typelem) = oid AS isarray FROM pg_type
LOG:  terminating any other active server processes
WARNING:  terminating connection because of crash of another server process
DETAIL:  The postmaster has commanded this server process to roll back the current transaction and exit, because another server process exited abnormally and possibly corrupted shared memory.
HINT:  In a moment you should be able to reconnect to the database and repeat your command.
postgres@cuda-server:~$ LOG:  all server processes terminated; reinitializing
LOG:  database system was interrupted; last known up at 2016-02-12 17:03:58 CET
LOG:  database system was not properly shut down; automatic recovery in progress
LOG:  invalid record length at 1/945B6F80
LOG:  redo is not required
LOG:  MultiXact member wraparound protections are now enabled
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
```

**Comment by kaigai** [comment] 2016-02-12 23:40
Thanks, the later one seems to me another independent bug around treatment of system columns.

I'll investigate both. Please wait for a while.

**Comment by kaigai** [comment] 2016-02-13 14:58
Fixed at f8d4515784b03bf7562e4fb78bb8551dc8874859, fa6cc556bb717a4df9767016f62ee1b0f3da4800, and 4e78d4fef4e15c82dfbcf3e012d357b9b0bed1b6

Regarding to the original problem, it didn't pass the WHERE clause to code generator in case when GpuScan is injected on the post-planner-hook. In the result, the generated GPU code evaluates as if every rows satisfy the WHERE clause, then GpuScan produced rows that have id != 91.

On the latest code:
```
hoge=# SELECT detected_proto_id FROM small_flow f
  WHERE f.detected_proto_id = 91 LIMIT 5;
 detected_proto_id
-------------------
                91
                91
                91
                91
                91
(5 rows)
```

The second problem was simple functionality lack, so add system column handling on Gpu Projection code.

**Comment by JulianIntronati** [comment] 2016-02-15 14:56
First, thank you, I really appreciate your reactivity.

Well, I tried your new version and it correct the "bug" for the simple query. But ... I encounter the same kind of strange behavior for a bigger query.

Here are the test case on the test_2 database [(download here)](https://drive.google.com/file/d/0B-7ItTIkvEGUQTNZTEtxUTRLQ1k/view?usp=sharing) :
```
SET pg_strom.enabled TO on;
SELECT                     
  f.dst_device_id AS name,
  SUM(so_packets_length) AS so_weight,
  SUM(do_packets_length) AS do_weight
FROM
  s_flow f
  LEFT JOIN s_http_flow hf ON f.id = hf.flow_id
WHERE
  ( 
    (
      hf.flow_id IS NULL AND ( f.master_proto_id = 91 OR f.detected_proto_id = 91 )
    ) OR (
      hf.flow_id IS NOT NULL
    )
  )
GROUP BY name
ORDER BY name;
```
Name | so_weight | do_weight |
------------ | ------------- | ------------- | ------------- |
    1 |       13207 |        8791|
    2 |  4223144897 | 41122569063|
    3 |  1685160663 |   542842623|
    4 | 10750392967 | 40344351323|
    7 |      361559 |      209747|
    8 |      207434 |      311821|
    9 |      237304 |      178997|
   10 |     2531881 |      539273|
   11 |     2952288 |    40575719|
   12 |          61 |           0|
   13 |      409400 |      414019|
   16 |        2088 |         240|
   17 |      265178 |      129787|
   18 |     2156464 |        1768|
   19 |        2174 |           0|
   21 |       94678 |       42276|
   25 |       32986 |       30223|
   26 |    12678928 |    12445673|
   29 |      335084 |      107933|
   30 |      327816 |      165635|
   31 |       78306 |       59507|
   33 |       64720 |       12479|
   34 |       27951 |        3946|
   35 |       58673 |       25864|
   37 |    55223010 |           0|
   38 |    57594855 |           0|
   40 |    25529809 |           0|
   41 |    26515915 |           0|
   42 |    16336580 |           0|
   43 |     1576100 |           0|
   47 |      267522 |      122122|
   50 |       35149 |       16182|
   53 |        2330 |        1128|
   56 |    12883907 |      175489|
   57 |      418224 |      582419|
   58 |   117478140 |    69941582|
   59 |      103167 |       43591|
   60 |     3408600 |           0|
   61 |      715641 |           0|
   62 |      120299 |        1187|
   64 |        1380 |         192|
   68 |          66 |          60|
   69 |      869314 |           0|
   70 |    20489440 |           0|
   71 |      439181 |           0|
   72 |        5504 |           0|
   73 |         258 |           0|
   74 |       34020 |           0|
   75 |       15990 |           0|
   76 |      109138 |           0|
   77 |         312 |           0|
   78 |         156 |           0|
   79 |          78 |           0|
   80 |       36634 |           0|
   82 |         156 |           0|
   83 |       13802 |        7243|
   84 |         156 |           0|
   85 |        6594 |           0|
   86 |     2056442 |           0|
   87 |        5106 |         360|
   88 |        2048 |           0|
   89 |         390 |           0|
   90 |        1614 |           0|
   91 |          66 |           0|
   92 |          78 |           0|
   93 |       41720 |          60|
   94 |         344 |           0|
   96 |         312 |           0|
   97 |        1794 |           0|
   98 |        1680 |         600|
   99 |         312 |           0|
  100 |         258 |           0|
  101 |        3055 |         240|
  102 |          78 |           0|
  103 |          78 |           0|
  104 |         156 |           0|
  105 |         858 |           0|
  106 |         312 |           0|
  107 |       25509 |       17602|
  108 |         156 |           0|
  109 |         234 |           0|
  110 |          78 |           0|
  111 |         468 |           0|
  112 |       11091 |        3793|
  113 |        4602 |           0|
  115 |          78 |           0|
  116 |          82 |           0|
  117 |         164 |           0|
  118 |         567 |           0|
  119 |         702 |           0|
  120 |       66740 |           0|
  121 |         420 |         540|
  122 |        2500 |           0|
  123 |        2064 |           0|
  124 |        1762 |         252|
  125 |          78 |           0|
  126 |          78 |           0|
  127 |        9347 |        9955|
  128 |         390 |           0|
  129 |          78 |           0|
  130 |         156 |           0|
  131 |         164 |           0|
  132 |        2580 |         300|
  133 |         156 |           0|
  134 |      443250 |           0|
  135 |          82 |           0|
  136 |        5572 |           0|
  137 |          78 |           0|
  138 |        7332 |           0|
  142 |         884 |           0|
  143 |         410 |           0|
  144 |        2635 |         391|
  145 |         156 |           0|
  146 |         156 |           0|
  147 |         390 |           0|
  148 |       20135 |       21138|
  149 |         406 |           0|
  150 |         156 |           0|
  151 |         180 |         120|
  152 |         396 |           0|
  153 |          78 |           0|
(121 rows)

```
SET pg_strom.enabled TO off;
SELECT                     
  f.dst_device_id AS name,
  SUM(so_packets_length) AS so_weight,
  SUM(do_packets_length) AS do_weight
FROM
  s_flow f
  LEFT JOIN s_http_flow hf ON f.id = hf.flow_id
WHERE
  ( 
    (
      hf.flow_id IS NULL AND ( f.master_proto_id = 91 OR f.detected_proto_id = 91 )
    ) OR (
      hf.flow_id IS NOT NULL
    )
  )
GROUP BY name
ORDER BY name;
```
Name | so_weight | do_weight |
------------ | ------------- | ------------- | ------------- |
    1 |      10327 |        6931|
    2 | 2074092627 | 37995295745|
    3 |   70652705 |   327333915|
    4 | 8428770795 | 38443138215|
    7 |     170375 |       53009|
    8 |     119030 |      241207|
    9 |     134393 |      107327|
   10 |       1620 |         466|
   11 |    2704937 |    40027169|
   13 |     389270 |      394819|
   16 |        960 |          60|
   17 |     146342 |       49807|
   18 |       1082 |           0|
   21 |      21929 |       19596|
   25 |      24959 |       24523|
   26 |       2200 |         386|
   29 |     157437 |       25673|
   30 |     259697 |      122141|
   31 |      47684 |       40695|
   33 |      17487 |        5343|
   34 |       8179 |        2770|
   35 |      50679 |       24052|
   47 |     161116 |       26182|
   50 |      19817 |        6750|
   56 |      10439 |       19111|
   57 |     264131 |      563015|
   58 |     213156 |      202457|
   59 |      55104 |        2731|
   62 |      46079 |         995|
   83 |       3680 |        3625|
   87 |       4146 |         240|
   98 |        360 |         120|
  101 |        240 |         240|
  107 |      12135 |        9922|
  112 |       8611 |        3157|
  121 |        180 |         120|
  124 |        326 |           0|
  127 |       9347 |        9955|
  132 |       2100 |         180|
  144 |        300 |         211|
  148 |       7140 |        9900|
  151 |         60 |           0|
(42 rows)


As you can see it seems to not filtering out the where clause properly.

The pg_dump "new feature" seems to be working properly.

If you need more informations, just ask for it.

**Comment by kaigai** [comment] 2016-02-16 00:17
Sorry for this inconvenience.

I could reproduce the problem, and tried to identify source of the problem.

When pg_strom.enable_gpupreagg=off => same problem reproduced
When pg_strom.enable_gpuhashjoin=off => problem was not reproduced

When I rewrite "LEFT JOIN" by "JOIN" => problem was not reproduced.

It seems to me a bug around outer join of GpuHashJoin.
Let me investigate it more deeply. Please wait for a while.

**Comment by kaigai** [comment] 2016-02-16 07:37
It was fixed at d8b01fd58b8fa64a57f0e1b946a63f1758335946

This join contains two different qualifiers
- ON f.id = hf.flow_id
- WHERE ....
```
SELECT                     
  f.dst_device_id AS name,
  SUM(so_packets_length) AS so_weight,
  SUM(do_packets_length) AS do_weight
FROM
  s_flow f
  LEFT JOIN s_http_flow hf ON f.id = hf.flow_id
WHERE
  ( 
    (
      hf.flow_id IS NULL AND ( f.master_proto_id = 91 OR f.detected_proto_id = 91 )
    ) OR (
      hf.flow_id IS NOT NULL
    )
  )
GROUP BY name
ORDER BY name;
```
LEFT OUTER JOIN generates a row but with NULL value on inner-side, if no matched inner tuple found.
At that time, ON clause shall be used to check whether the outer tuple is matched with this inner tuple. However, the previous code checked ON clause + WHERE clause simultaneously.
It leads differences in the results, and eventually leads the incorrect output.

```
test2=# SELECT
  f.dst_device_id AS name,
  SUM(so_packets_length) AS so_weight,
  SUM(do_packets_length) AS do_weight
FROM
  s_flow f
  LEFT JOIN s_http_flow hf ON f.id = hf.flow_id
WHERE
  (
    (
      hf.flow_id IS NULL AND ( f.master_proto_id = 91 OR f.detected_proto_id = 91 )
    ) OR (
      hf.flow_id IS NOT NULL
    )
  )
GROUP BY name
ORDER BY name;
 name | so_weight  |  do_weight
------+------------+-------------
    1 |      10327 |        6931
    2 | 2074092627 | 37995295745
    3 |   70652705 |   327333915
    4 | 8428770795 | 38443138215
    7 |     170375 |       53009
    8 |     119030 |      241207
    9 |     134393 |      107327
   10 |       1620 |         466
   11 |    2704937 |    40027169
   13 |     389270 |      394819
   16 |        960 |          60
   17 |     146342 |       49807
   18 |       1082 |           0
   21 |      21929 |       19596
   25 |      24959 |       24523
   26 |       2200 |         386
   29 |     157437 |       25673
   30 |     259697 |      122141
   31 |      47684 |       40695
   33 |      17487 |        5343
   34 |       8179 |        2770
   35 |      50679 |       24052
   47 |     161116 |       26182
   50 |      19817 |        6750
   56 |      10439 |       19111
   57 |     264131 |      563015
   58 |     213156 |      202457
   59 |      55104 |        2731
   62 |      46079 |         995
   83 |       3680 |        3625
   87 |       4146 |         240
   98 |        360 |         120
  101 |        240 |         240
  107 |      12135 |        9922
  112 |       8611 |        3157
  121 |        180 |         120
  124 |        326 |           0
  127 |       9347 |        9955
  132 |       2100 |         180
  144 |        300 |         211
  148 |       7140 |        9900
  151 |         60 |           0
(42 rows)
```
Thanks for such a corner case!

**Comment by JulianIntronati** [comment] 2016-02-18 10:48
I tested your new patch and it's seems to be working perfectly even inside a bigger request.

For now I can say that you solved the issue.

Thanks a lot. I will continue to use your software and contact you if I found some weirdness ! This project is really interesting and really promising.

**Comment by JulianIntronati** [comment] 2016-02-19 14:37
After some more testing I fall in this new strange behavior ...

You can download dataset [(download here)](https://drive.google.com/file/d/0B-7ItTIkvEGUa3hNOC1PWGc5ZmM/view?usp=sharing) :

Disabling pg_strom
```
test_3=# SET pg_strom.enabled TO off;
SET
test_3=# SELECT                      
  f.dst_device_id AS name,
  SUM(so_packets_length) AS so_weight,
  SUM(do_packets_length) AS do_weight
FROM
  s_flow f
  LEFT JOIN s_http_flow hf ON f.id = hf.flow_id
WHERE
  f.timestamp BETWEEN '1449356400' AND '1449442799'
  AND ( 
    (
      hf.flow_id IS NULL AND ( f.master_proto_id = 91 OR f.detected_proto_id = 91 )
    ) OR (
      hf.flow_id IS NOT NULL
    )
  )
GROUP BY name
;
 name | so_weight | do_weight 
------+-----------+-----------
   56 |       180 |         0
   62 |      1540 |         0
   25 |        60 |        60
    8 |        60 |         0
    2 |  15316002 | 253786440
    3 |   1532095 |   2485885
   10 |       120 |         0
   26 |        60 |         0
   11 |    121528 |   1996366
    4 |  14880992 | 254289155
   18 |        60 |         0
   13 |     16200 |     16291
(12 rows)
```
Enabling pg_strom
```
test_3=# SET pg_strom.enabled TO on;
SET
test_3=# SELECT                      
  f.dst_device_id AS name,
  SUM(so_packets_length) AS so_weight,
  SUM(do_packets_length) AS do_weight
FROM
  s_flow f
  LEFT JOIN s_http_flow hf ON f.id = hf.flow_id
WHERE
  f.timestamp BETWEEN '1449356400' AND '1449442799'
  AND ( 
    (
      hf.flow_id IS NULL AND ( f.master_proto_id = 91 OR f.detected_proto_id = 91 )
    ) OR (
      hf.flow_id IS NOT NULL
    )
  )
GROUP BY name
;
 name | so_weight | do_weight 
------+-----------+-----------
   43 |       540 |         0
   25 |       240 |       300
    8 |      1020 |       840
   10 |     73581 |     22140
   42 |    484732 |         0
   26 |   1584156 |   1229956
   11 |    127322 |   2008917
   38 |   2413225 |         0
    4 | 223248209 | 369329646
   18 |     34207 |         0
   69 |     37756 |         0
   13 |     16320 |     16411
   60 |    113964 |         0
   37 |    872149 |         0
    7 |       360 |       240
   16 |        60 |       120
   40 |    245371 |         0
   56 |       660 |       480
   53 |       114 |         0
   62 |     12695 |         0
   71 |     28080 |         0
    2 |  74222541 | 317103413
    3 |   9906925 |   4607550
   41 |    233786 |         0
   61 |     17260 |         0
(25 rows)
```

**Comment by kaigai** [comment] 2016-02-22 01:00
Timestamp comparison seems to me doubtful.....
Could you wait for a few days? I cannot make enough time in the early half of this week.

**Comment by JulianIntronati** [comment] 2016-02-23 10:37
It's okay.

Just in case for if you missed it, the timestamp is not qualified as type "timestamp" but as type "integer", don't know if it's important for your investigation.

I'm waiting for your conclusion.
Best regards.

**Comment by kaigai** [comment] 2016-03-01 09:04
Thanks for your report.

The problem was, tuples generated by GpuRighHashJoin were not checked by non-join-quals (*1).
This oversight produced more rows than expectations, then lead incorrect result.

Could you try the latest commit in "dynjoin" branch? It is my development branch to be merged
into "master" after the final checks.

```
test3=# set pg_strom.enabled = on;
SET
test3=# set enable_hashjoin = off;
SET
test3=# SELECT
  f.dst_device_id AS name,
  SUM(so_packets_length) AS so_weight,
  SUM(do_packets_length) AS do_weight
FROM
  s_flow f
  LEFT JOIN s_http_flow hf ON f.id = hf.flow_id
WHERE
  f.timestamp BETWEEN '1449356400' AND '1449442799'
  AND (
    (
      hf.flow_id IS NULL AND ( f.master_proto_id = 91 OR f.detected_proto_id = 91 )
    ) OR (
      hf.flow_id IS NOT NULL
    )
  )
GROUP BY name
;
 name | so_weight | do_weight
------+-----------+-----------
   56 |       180 |         0
   62 |      1540 |         0
   25 |        60 |        60
    8 |        60 |         0
    2 |  15316002 | 253786440
    3 |   1532095 |   2485885
   10 |       120 |         0
   26 |        60 |         0
   11 |    121528 |   1996366
    4 |  14880992 | 254289155
   18 |        60 |         0
   13 |     16200 |     16291
(12 rows)
```

**Comment by JulianIntronati** [comment] 2016-03-01 10:40
Well I tested it, it seems to be working properly.

Keep doing this good work !
Thank you.

**Closed** 2016-03-01 11:42 UTC
Labels: bug
